---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - name: Install Python 3 and pip
      package:
        name:
          - python3
          - py3-pip
        state: present

    - name: Install Python libraries via apk
      package:
        name:
          - py3-requests
          - py3-packaging
        state: present

  roles:
    - role: pyronear.openvpn
