---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  - name: server_container
    image: docker:27-dind
    privileged: true
    command: "dockerd-entrypoint.sh"
    groups:
      - openvpn_server
  - name: client_container
    image: ubuntu:24.04
    privileged: true
    groups:
      - openvpn_client
provisioner:
  name: ansible
  options:
    skip-tags: reboot
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
  enabled: true
