---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  - name: openvpn
    image: docker:27-dind
    privileged: true
    command: "dockerd-entrypoint.sh"
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
  enabled: True
