---
dependency:
  name: galaxy
driver:
  name: default
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
