- name: Verify Openvpn Server
  hosts: openvpn_server
  gather_facts: true
  tasks:
  - stat:
      path: '/srv/openvpn/passphrase.txt'
    register: passphrase

  - stat:
      path: '/srv/openvpn/openvpn.conf'
    register: conf
 
  - name: tests
    assert:
      that:
      - "passphrase.stat.mode == '0600'"
      - "conf.stat.exists"

- name: Verify Openvpn Client
  hosts: openvpn_client
  gather_facts: true
  tasks:
  - stat:
      path: '/etc/openvpn/auth.txt'
    register: auth

  - name: tests
    assert:
      that:
      - "auth.stat.mode == '0600'"
